// Code generated by mockery v1.0.0. DO NOT EDIT.

package gui

import (
	color "image/color"

	mock "github.com/stretchr/testify/mock"
)

// MockCanvas is an autogenerated mock type for the Canvas type
type MockCanvas struct {
	mock.Mock
}

// BrailleToScreen provides a mock function with given fields: _a0
func (_m *MockCanvas) BrailleToScreen(_a0 string) {
	_m.Called(_a0)
}

// NewCircle provides a mock function with given fields: _a0
func (_m *MockCanvas) NewCircle(_a0 color.Color) {
	_m.Called(_a0)
}

// VapeLightOff provides a mock function with given fields: _a0
func (_m *MockCanvas) VapeLightOff(_a0 int) {
	_m.Called(_a0)
}
