// Code generated by mockery v1.0.0. DO NOT EDIT.

package gui

import mock "github.com/stretchr/testify/mock"

// mockPinProcessor is an autogenerated mock type for the pinProcessor type
type mockPinProcessor struct {
	mock.Mock
}

// High provides a mock function with given fields:
func (_m *mockPinProcessor) High() {
	_m.Called()
}

// Low provides a mock function with given fields:
func (_m *mockPinProcessor) Low() {
	_m.Called()
}

// Output provides a mock function with given fields:
func (_m *mockPinProcessor) Output() {
	_m.Called()
}
