// Code generated by mockery v1.0.0. DO NOT EDIT.

package gui

import mock "github.com/stretchr/testify/mock"

// mockRpioProcessor is an autogenerated mock type for the rpioProcessor type
type mockRpioProcessor struct {
	mock.Mock
}

// Open provides a mock function with given fields:
func (_m *mockRpioProcessor) Open() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Pin provides a mock function with given fields: p
func (_m *mockRpioProcessor) Pin(p int) pinProcessor {
	ret := _m.Called(p)

	var r0 pinProcessor
	if rf, ok := ret.Get(0).(func(int) pinProcessor); ok {
		r0 = rf(p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pinProcessor)
		}
	}

	return r0
}
