// Code generated by mockery v1.0.0. DO NOT EDIT.

package gui

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockScreen is an autogenerated mock type for the Screen type
type MockScreen struct {
	mock.Mock
}

// AllVapesOff provides a mock function with given fields:
func (_m *MockScreen) AllVapesOff() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Close provides a mock function with given fields:
func (_m *MockScreen) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Cols provides a mock function with given fields:
func (_m *MockScreen) Cols() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// DisplayMatrix provides a mock function with given fields: matrix, displayDuration
func (_m *MockScreen) DisplayMatrix(matrix [][]int, displayDuration time.Duration) error {
	ret := _m.Called(matrix, displayDuration)

	var r0 error
	if rf, ok := ret.Get(0).(func([][]int, time.Duration) error); ok {
		r0 = rf(matrix, displayDuration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Rows provides a mock function with given fields:
func (_m *MockScreen) Rows() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}
