// Code generated by mockery v1.0.0. DO NOT EDIT.

package gui

import mock "github.com/stretchr/testify/mock"

// mockTerminalOutputter is an autogenerated mock type for the terminalOutputter type
type mockTerminalOutputter struct {
	mock.Mock
}

// Printf provides a mock function with given fields: format, a
func (_m *mockTerminalOutputter) Printf(format string, a ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, a...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, ...interface{}) error); ok {
		r0 = rf(format, a...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
